# Generated by Django 4.0.1 on 2022-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
