# Generated by Django 4.0.1 on 2022-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_data_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_data',
            name='population',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
    ]
