# Generated by Django 4.0.1 on 2022-02-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_country_data_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_data',
            name='population',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
