# Generated by Django 4.0.1 on 2022-02-24 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_country_data_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_data',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country_data',
            name='population',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
