# Generated by Django 4.0.1 on 2022-02-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_country_data_author_country_data_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_data',
            name='author',
        ),
        migrations.RemoveField(
            model_name='country_data',
            name='created',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
