# Generated by Django 4.0.1 on 2022-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_country_data_liked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_data',
            name='population',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
