# Generated by Django 4.0.1 on 2022-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_country_data_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_data',
            name='liked',
        ),
        migrations.AlterField(
            model_name='country_data',
            name='population',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
